### PR TITLE
RIP

### PR DESCRIPTION
**Pull request by ndeloof**
Sorry guys for the bad joke, couldn't resist.

### CODE REVIEW

**Comment by gberche-orange** [comment]
so nice, thanks for your encouragements.

**Comment by ndeloof** [comment]
just can't believe the project is still alive, considering all opensource modern alternatives to do the job

**Comment by gberche-orange** [comment]
The project went through some deep transformation since we collaborated together few years ago. If you're interested you might checkout https://github.com/Orange-OpenSource/elpaaso#introduction to learn more about history of the project, current status, and where we're going. 

We do agree though that ElPaaso still needs to transform to better reach its goals, and we're always happy to hear constructive suggestions and critics.

**Comment by ndeloof** [comment]
yes I've already seen that, but considering modern PaaS do all embrace containers, I wonder this "_new_" el-passo design can be considered a viable thing.
Just reading "_WSDL contract for SOAP API_" in description makes me think I'm back in 2000's

**Comment by gberche-orange** [comment]
So you're main concern is that elpaaso promotes a language-level contract (buildpacks) for pushing apps, and not an os-level contract (Linux containers) ?

**Comment by ArthurHlt** [comment]
Well elpaaso is not a PaaS if you look at the really first line of the link Guillaume sent to you but an addon to cloudfoundry. It doesn't seem this is accurate to talk about container or maybe you just don't know how should be considered containers.

About the soap api, it answer to a need that rest doesn't have, btw rest is much older than soap ...
Anyway, how services are called between components doesn't really matter for users. 

And to be childish as you were, man open you eyes you're working on jenkins and you're talking about our work. A open source cool stuff which prove jenkins is old: take a look at http://concourse.ci/ ...

**Comment by ndeloof** [comment]
nice to see you have nice argumentation to address trolls like I did here :)
have fun on this project

**Pull request closed without merging**
